'use client';
import { FormEvent, useEffect, useState } from 'react';
import { clientApi } from '../../../lib/client-api';
import styles from '../portal.module.css';
type Company = { codeFodip: string; raisonSociale: string; nomCommercial?: string; rccm?: string; nif?: string; formeJuridique?: string; dateCreation?: string; descriptionActivite?: string; nombreEmployes: number; telephone?: string; email?: string; };
export default function CompanyProfilePage() {
  const [form, setForm] = useState<Company | null>(null); const [message, setMessage] = useState('');
  useEffect(() => { clientApi<Company>('/api/pme/entreprise').then(setForm).catch((e) => setMessage(e.message)); }, []);
  function change<K extends keyof Company>(key: K, value: Company[K]) { setForm((current) => current ? { ...current, [key]: value } : current); }
  async function save(event: FormEvent) { event.preventDefault(); if (!form) return; setMessage(''); try { const updated = await clientApi<Company>('/api/pme/entreprise', { method: 'PATCH', body: JSON.stringify({ raisonSociale: form.raisonSociale, nomCommercial: form.nomCommercial || undefined, rccm: form.rccm || undefined, nif: form.nif || undefined, formeJuridique: form.formeJuridique || undefined, dateCreation: form.dateCreation || undefined, descriptionActivite: form.descriptionActivite || undefined, nombreEmployes: Number(form.nombreEmployes || 0), telephone: form.telephone || undefined, email: form.email || undefined }) }); setForm(updated); setMessage('Modifications enregistrées.'); } catch (e) { setMessage(e instanceof Error ? e.message : 'Enregistrement impossible'); } }
  if (!form) return <main className={styles.main}><h1 className={styles.title}>Fiche entreprise</h1><p>{message || 'Chargement…'}</p></main>;
  return <main className={styles.main}><p className={styles.eyebrow}>Mon entreprise · {form.codeFodip}</p><h1 className={styles.title}>Fiche entreprise</h1><p className={styles.lead}>Ces informations proviennent désormais de PostgreSQL et sont limitées à votre entreprise.</p><form className={`${styles.card} ${styles.formCard} ${styles.section}`} onSubmit={save}><div className={styles.formGrid}><div className={styles.field}><label htmlFor="raisonSociale">Raison sociale</label><input id="raisonSociale" required value={form.raisonSociale ?? ''} onChange={(e) => change('raisonSociale', e.target.value)} /></div><div className={styles.field}><label htmlFor="nomCommercial">Nom commercial</label><input id="nomCommercial" value={form.nomCommercial ?? ''} onChange={(e) => change('nomCommercial', e.target.value)} /></div><div className={styles.field}><label htmlFor="rccm">RCCM</label><input id="rccm" value={form.rccm ?? ''} onChange={(e) => change('rccm', e.target.value)} /></div><div className={styles.field}><label htmlFor="nif">NIF</label><input id="nif" value={form.nif ?? ''} onChange={(e) => change('nif', e.target.value)} /></div><div className={styles.field}><label htmlFor="formeJuridique">Forme juridique</label><input id="formeJuridique" value={form.formeJuridique ?? ''} onChange={(e) => change('formeJuridique', e.target.value)} /></div><div className={styles.field}><label htmlFor="dateCreation">Date de création</label><input id="dateCreation" type="date" value={(form.dateCreation ?? '').slice(0, 10)} onChange={(e) => change('dateCreation', e.target.value)} /></div><div className={styles.field}><label htmlFor="nombreEmployes">Nombre d'employés</label><input id="nombreEmployes" type="number" min="0" value={form.nombreEmployes ?? 0} onChange={(e) => change('nombreEmployes', Number(e.target.value))} /></div><div className={styles.field}><label htmlFor="telephone">Téléphone</label><input id="telephone" value={form.telephone ?? ''} onChange={(e) => change('telephone', e.target.value)} /></div><div className={`${styles.field} ${styles.fieldFull}`}><label htmlFor="email">Email</label><input id="email" type="email" value={form.email ?? ''} onChange={(e) => change('email', e.target.value)} /></div><div className={`${styles.field} ${styles.fieldFull}`}><label htmlFor="descriptionActivite">Description de l'activité</label><textarea id="descriptionActivite" value={form.descriptionActivite ?? ''} onChange={(e) => change('descriptionActivite', e.target.value)} /></div></div>{message && <div className={styles.notice}>{message}</div>}<div className={styles.buttonRow}><button className={styles.primary}>Enregistrer les modifications</button></div></form></main>;
}
