'use client';
import { FormEvent, useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { clientApi } from '../../../lib/client-api';
import styles from '../portal.module.css';
type Program = { id: string; nom: string; description?: string; montantMin?: string; montantMax?: string };
export default function FundingApplicationPage() {
  const router = useRouter(); const [programs, setPrograms] = useState<Program[]>([]); const [programmeId, setProgrammeId] = useState(''); const [montant, setMontant] = useState(''); const [apport, setApport] = useState('0'); const [objet, setObjet] = useState(''); const [description, setDescription] = useState(''); const [emplois, setEmplois] = useState('0'); const [message, setMessage] = useState('');
  useEffect(() => { clientApi<Program[]>('/api/programmes').then((items) => { setPrograms(items); if (items[0]) setProgrammeId(items[0].id); }).catch((e) => setMessage(e.message)); }, []);
  async function save(event: FormEvent) { event.preventDefault(); setMessage(''); try { await clientApi('/api/pme/dossiers', { method: 'POST', body: JSON.stringify({ programmeId, montantDemande: Number(montant), apportPersonnel: Number(apport || 0), objetFinancement: objet, descriptionProjet: description || undefined, nombreEmploisPrevus: Number(emplois || 0) }) }); router.push('/entrepreneur/suivi'); router.refresh(); } catch (e) { setMessage(e instanceof Error ? e.message : 'Création impossible'); } }
  return <main className={styles.main}><p className={styles.eyebrow}>Nouvelle demande</p><h1 className={styles.title}>Demande de financement</h1><p className={styles.lead}>Le brouillon est enregistré dans PostgreSQL pour votre entreprise authentifiée.</p><form className={`${styles.card} ${styles.formCard} ${styles.section}`} onSubmit={save}><div className={styles.formGrid}><div className={`${styles.field} ${styles.fieldFull}`}><label>Programme</label><select required value={programmeId} onChange={(e) => setProgrammeId(e.target.value)}><option value="">Sélectionner</option>{programs.map((p) => <option key={p.id} value={p.id}>{p.nom}</option>)}</select></div><div className={styles.field}><label>Montant demandé (GNF)</label><input required type="number" min="1" value={montant} onChange={(e) => setMontant(e.target.value)} /></div><div className={styles.field}><label>Apport personnel (GNF)</label><input type="number" min="0" value={apport} onChange={(e) => setApport(e.target.value)} /></div><div className={`${styles.field} ${styles.fieldFull}`}><label>Objet du financement</label><input required value={objet} onChange={(e) => setObjet(e.target.value)} /></div><div className={`${styles.field} ${styles.fieldFull}`}><label>Description du projet</label><textarea value={description} onChange={(e) => setDescription(e.target.value)} /></div><div className={styles.field}><label>Emplois directs prévus</label><input type="number" min="0" value={emplois} onChange={(e) => setEmplois(e.target.value)} /></div></div><div className={styles.notice}>Après l’enregistrement, utilisez « Documents » dans le suivi pour déposer vos pièces justificatives de manière sécurisée.</div>{message && <div className={styles.notice}>{message}</div>}<div className={styles.buttonRow}><button className={styles.primary}>Enregistrer le brouillon</button></div></form></main>;
}
