'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { clientApi } from '../../lib/client-api';
import styles from './portal.module.css';
type Company = { codeFodip: string; raisonSociale: string }; type Application = { id: string; statut: string }; type Program = { id: string; nom: string; description?: string };
export default function EntrepreneurDashboard() {
  const [company, setCompany] = useState<Company | null>(null); const [dossiers, setDossiers] = useState<Application[]>([]); const [programs, setPrograms] = useState<Program[]>([]); const [error, setError] = useState('');
  useEffect(() => { Promise.all([clientApi<Company>('/api/pme/entreprise'), clientApi<Application[]>('/api/pme/dossiers'), clientApi<Program[]>('/api/programmes')]).then(([c, d, p]) => { setCompany(c); setDossiers(d); setPrograms(p); }).catch((e) => setError(e.message)); }, []);
  const drafts = dossiers.filter((d) => d.statut === 'BROUILLON').length; const active = dossiers.filter((d) => !['BROUILLON', 'CLOTURE', 'REJETE'].includes(d.statut)).length;
  return <main className={styles.main}><p className={styles.eyebrow}>Espace entrepreneur</p><h1 className={styles.title}>{company ? `Bienvenue, ${company.raisonSociale}` : 'Votre espace FODIP'}</h1><p className={styles.lead}>Votre tableau de bord utilise désormais les données de votre session et de PostgreSQL.</p>{error && <div className={styles.notice}>{error}</div>}<section className={styles.hero}><div className={`${styles.card} ${styles.heroCard}`}><h2>{dossiers.length} dossier(s)</h2><p>{drafts} brouillon(s) · {active} dossier(s) en traitement.</p><div className={styles.buttonRow}><Link className={styles.primary} href="/entrepreneur/demande">Nouvelle demande</Link><Link className={styles.secondary} href="/entrepreneur/suivi">Voir mes dossiers</Link></div></div><div className={`${styles.card} ${styles.quick}`}><p className={styles.eyebrow}>Référence PME</p><strong>{company?.codeFodip ?? '—'}</strong><small>Identité chargée depuis votre entreprise associée.</small></div></section><section className={styles.section}><div className={styles.sectionHeader}><div><h2>Programmes actifs</h2><p>Référentiel chargé depuis l’API FODIP.</p></div></div><div className={styles.programs}>{programs.map((p) => <article className={`${styles.card} ${styles.program}`} key={p.id}><h3>{p.nom}</h3><p>{p.description ?? 'Programme de financement FODIP.'}</p></article>)}</div></section></main>;
}
