from pathlib import Path
import re
import sys

# Reference-table IDs are generated by migrations and are not public/business identifiers.
# Demo scenarios may keep deterministic IDs for their own entities (PMEs, dossiers, users, etc.),
# but institutional references must be resolved by stable codes so migrations can evolve safely.
FORBIDDEN_REFERENCE_UUID_PREFIXES = {
    "region": re.compile(r"10000000-0000-4000-8000-[0-9a-f-]+", re.IGNORECASE),
    "secteur": re.compile(r"20000000-0000-4000-8000-[0-9a-f-]+", re.IGNORECASE),
    "modele_scoring": re.compile(r"70000000-0000-4000-8000-[0-9a-f-]+", re.IGNORECASE),
    "critere_scoring": re.compile(r"71000000-0000-4000-8000-[0-9a-f-]+", re.IGNORECASE),
}

errors: list[str] = []
seed_dir = Path("database/seeds")
files = sorted(seed_dir.glob("*.sql"))

if not files:
    errors.append("No Docker/demo seed SQL files found")

for path in files:
    text = path.read_text(encoding="utf-8")
    for reference_name, pattern in FORBIDDEN_REFERENCE_UUID_PREFIXES.items():
        matches = sorted(set(pattern.findall(text)))
        if matches:
            errors.append(
                f"{path}: hard-coded {reference_name} reference UUID(s) {', '.join(matches)}; "
                "resolve institutional references by stable code instead"
            )

if errors:
    print("\n".join(errors), file=sys.stderr)
    raise SystemExit(1)

print(f"Validated {len(files)} seed file(s): institutional references use stable business codes.")
